name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy
    
    - name: Run Ruff formatter check
      run: |
        ruff format --check .
      continue-on-error: true
    
    - name: Run Ruff linter
      run: |
        ruff check . --output-format=github
      continue-on-error: true
    
    - name: Run MyPy type checker
      run: |
        mypy src/ --no-error-summary
      continue-on-error: true
